/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import EXCEL.Evaluacion;
import javax.swing.UIManager;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author luisg
 */
public class Registrarse extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public Registrarse() {
        initComponents();
        this.setTitle("Login");
        this.setLocationRelativeTo(null);
    }
    
    public Connection conectar(){
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_de_proyectos", "root","");
            
        } catch (Exception e) {
            System.err.print(e.toString());
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado");
        }
        return con;
    }
    
    public void crear(){
        Connection con1 = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        String user =  usuario_JTF.getText();
        String pass = pass_jpf.getText();
        String nombre = nombre_jtf.getText();
        String apellidoP = apellido_p_jtf.getText();
        String apellidoM = apellido_m_jtf.getText();
        String correo = email_jtf.getText();
        if (user.equals("") || pass.equals("") || nombre.equals("") || apellidoP.equals("") || 
                apellidoM.equals("") || correo.equals("")) {
            JOptionPane.showMessageDialog(this, "uno de los campos esta vacio");
        }else{
            try {
                con1 = conectar();
                pst = con1.prepareStatement("INSERT INTO 'login' (`Nombre`, `Apellido_p`, `Apellido_M`, `Email`, `Usuario`, `Contraseña`) VALUES"
                        + "('"+nombre+"','"+apellidoP+"','"+apellidoM+"','"+ correo+"','"+user+"','"+pass+"')");
                pst.executeQuery();
            } catch (Exception e) {
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
  
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario_JTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JButton();
        pass_jpf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        apellido_m_jtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellido_p_jtf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombre_jtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email_jtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido Usuario");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Tratamiento_de_Datos\\icons\\profile.png")); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Tratamiento_de_Datos\\icons\\padlock.png")); // NOI18N
        jLabel3.setText("Contraseña");

        iniciar_sesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Tratamiento_de_Datos\\icons\\enter.png")); // NOI18N
        iniciar_sesion.setText("Iniciar sesion");
        iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_sesionActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Modelo de madures CMM\\icons\\profile.png")); // NOI18N
        jLabel4.setText("Apellido materno");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Modelo de madures CMM\\icons\\profile.png")); // NOI18N
        jLabel5.setText("Apellido paterno");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Modelo de madures CMM\\icons\\profile.png")); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisg\\Documents\\NetBeansProjects\\Modelo de madures CMM\\icons\\profile.png")); // NOI18N
        jLabel7.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addComponent(iniciar_sesion)
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario_JTF)
                    .addComponent(pass_jpf)
                    .addComponent(apellido_m_jtf)
                    .addComponent(apellido_p_jtf)
                    .addComponent(nombre_jtf)
                    .addComponent(email_jtf, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apellido_p_jtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellido_m_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(email_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_jpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(iniciar_sesion)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_sesionActionPerformed
        // TODO add your handling code here:
        crear();
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
        
    }//GEN-LAST:event_iniciar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_m_jtf;
    private javax.swing.JTextField apellido_p_jtf;
    private javax.swing.JTextField email_jtf;
    private javax.swing.JButton iniciar_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre_jtf;
    private javax.swing.JPasswordField pass_jpf;
    private javax.swing.JTextField usuario_JTF;
    // End of variables declaration//GEN-END:variables
}
